version: "3.4"

volumes:
  minio:

services:

  tpl:
    build: .
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock

  minio:
    image: minio/minio:RELEASE.2021-02-23T20-05-01Z
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

